name: pst-notebooks
channels:
  - conda-forge
dependencies:
  - flake8
  - ghp-import
  - ipython
  - joblib
  - matplotlib
  - numpy
  - opty
  - pydy
  - scipy
  - sphinx
  - sphinx-gallery
  - sympy
